### PR TITLE
Minor cloud tunings to improve cloud fraction and radiation in UFS

### PR DESCRIPTION
**Pull request by grantfirl**
All credit for code changes and description to @gthompsnWRF 

This PR is attempting to increase some cloud ice aloft explicitly in the Thompson microphysics by permitting a larger number of ice crystals (as a maximum) and by overall decreasing the fractional cloudiness in the Thompson cloud fraction scheme (```subroutine cal_cldfra3```).  The following list of 4 items describes the changes introduced by this PR:

1.  permit maximum of 5000 ice crystals per Liter (previously 500).
2.  return to using 10% of snow mass assumed as cloud ice in radiation scheme.
3.  alter the equation for cloud fraction to use ```SQRT(SQRT(expression))``` in place of a single square root (see graphic below for how that affects the outcome).
4.  for readability purposes, I added a blank line around some subroutines and removed authors initials ```hnhj``` because this author was already credited in a comment block and having initials on many lines is pointless.

The first two items listed above are intended to improve explicitly-created clouds by the microphysics whether or not the ```icloud = 3``` option is attempted.  The third item is an attempt to reduce what was seen as too much high-altitude ice cloud causing outgoing longwave radiation to be too low compared to the 240 W/m2 target value.

The graphic below represents the cloud fraction diagnosed as a function of relative humidity for a sample condition of approximately 13km horizontal grid spacing and 250m vertical level spacing to arrive at the Critical RH values of 0.82 over land (red) and 0.90 over ocean (blue).  Dashed lines are the older diagnosis and solid lines with dots are the outcome of the new code.

CF_versus_RH

### CODE REVIEW

**Comment by grantfirl** [comment]
Fixes https://github.com/NCAR/ccpp-physics/issues/966

**Comment by gthompsnWRF** [comment]
@grantfirl , @haiqinli :   Hi Grant. Thanks for doing this.  Can I make a simple request?  About 5 months ago, someone added a new boolean variable to the argument list called ```aero_ind_fdb``` at line#971 in ```module_mp_thompson.F90``` but the person who did it disrupts my original list of most important 2D and 3D variables.  While trying not to be a control freak, there's no reason to break my chain/list of variables (state and microphysics) with a boolean option.  I leave all the booleans and indicies and other "fluff" to the end of the subroutine arg list.

My request is simply moving this bool variable down the arg list to precede ```rand_perturb_on``` or anywhere among other bool vars of little consequence.  Would you consider this as a tiny change to enter into this PR?

**Comment by grantfirl** [comment]
> @grantfirl , @haiqinli : Hi Grant. Thanks for doing this. Can I make a simple request? About 5 months ago, someone added a new boolean variable to the argument list called `aero_ind_fdb` at line#971 in `module_mp_thompson.F90` but the person who did it disrupts my original list of most important 2D and 3D variables. While trying not to be a control freak, there's no reason to break my chain/list of variables (state and microphysics) with a boolean option. I leave all the booleans and indicies and other "fluff" to the end of the subroutine arg list.
> 
> My request is simply moving this bool variable down the arg list to precede `rand_perturb_on` or anywhere among other bool vars of little consequence. Would you consider this as a tiny change to enter into this PR?

@gthompsnWRF Sure thing, done: https://github.com/ufs-community/ccpp-physics/pull/1/commits/8cfde780f9d5f647ccd99cffe0e2d9e85d9def9b. I also added a check for the optional logical variable before it is used to avoid future errors.

**Comment by gthompsnWRF** [comment]
@grantfirl  The associated/prior PR had 2 positive reviews - one of which was Ruiyu.  Could we get those same reviewers again?

**Comment by grantfirl** [comment]
@ChunxiZhang-NOAA It looks like I don't have permissions in this repo to add reviewers. Can you add @RuiyuSun as a reviewer please?

**Review by ChunxiZhang-NOAA — APPROVED** [review]
Looks good for me. Greg and Ruiyu, please review it.

**Review by gthompsnWRF — APPROVED** [review]

**Pull request merged**
