### PR TITLE
Add fire coupling into ccpp physics including heat flux, upward specific humidity flux, and smoke tracer

### PR DESCRIPTION
**Pull request by danrosen25**
Add heat flux from fire, upward specific humidity flux from fire and the smoke tracer from fire into the ccpp physics package. Use the cpl_fire flag to enable coupling these values.

cpl_fire
hflx_fire
evap_fire
smoke_fire

Co-author: @masih-e

Resolves Issue #192

Testing
One of each compile line in the rt.conf tests was successfully executed on derecho. A new regression test for coupling atm and fire behavior (fbh) was added to rt.conf https://github.com/esmf-org/ufs-weather-model/tree/feature/ufs_fire_cpl

This is a draft pull request until the physics coupling for the community fire behavior model and ccpp physics is complete.

### CODE REVIEW

**Comment by grantfirl** [comment]
@danrosen25 Any updates on this draft PR?

**Comment by danrosen25** [comment]
@grantfirl
We're running through the RTs after some minor changes to make sure everything works. If we get clean results then we'll mark this as ready. The RTs take a long time to run, is there a recommended subset?

**Comment by grantfirl** [comment]
> @grantfirl We're running through the RTs after some minor changes to make sure everything works. If we get clean results then we'll mark this as ready. The RTs take a long time to run, is there a recommended subset?



> @grantfirl We're running through the RTs after some minor changes to make sure everything works. If we get clean results then we'll mark this as ready. The RTs take a long time to run, is there a recommended subset?

@danrosen25 No, unfortunately, they need to pass all of them. Be sure to turn ecflow on and they should run faster. E.g. set `-e` when running rt.sh.

**Comment by mkavulich** [comment]
@danrosen25 Just checking in to see what the status of this PR is, let me know if there's anything I can do to help things along.

**Comment by masih-e** [comment]
Hi, following up with the status of this PR. Please let me know if there is anything I can help with to move things along.

**Comment by danrosen25** [comment]
@mkavulich @masih-e 
Although the tests passed after the recent sync the "Files Changed" Look wrong. We only touched a few files. I think we'll need to sync using a squash or rebase onto the ufs/dev branch.

**Comment by mkavulich** [comment]
Dan, the problem seems to be because the fork was created from
https://github.com/NCAR/ccpp-physics, but the PR was opened to
https://github.com/ufs-community/ccpp-physics/. These repositories are
synced up regularly but they are not identical, and their histories are not
necessarily consistent, which is why we're seeing these odd diffs.

If you'd like me to rebase the changes from the old branch (from the NCAR
org) onto the ufs-dev branch in the ufs-community org I can do that, just
let me know. I have a bit of experience dealing with these two repos.

Michael Kavulich, Jr.
Associate Scientist, National Center for Atmospheric Research (NCAR)
Joint Numerical Testbed (JNT), Research Applications Laboratory (RAL)
***@***.*** ***@***.***>*

**Comment by masih-e** [comment]
Michael, would you be able to help with fixing the changes? Please let me know if I can help.

The files that we changed are the following: 
GFS_surface_composites_post.*
GFS_surface_generic_post.*
rrfs_smoke_wrapper.*

Thank you both for helping this moving forward

**Comment by mkavulich** [comment]
@masih-e @danrosen25 Sorry it took so long to get to this, I cherry-picked the appropriate commits and resolved the differences on my branch here: https://github.com/ufs-community/ccpp-physics/compare/ufs/dev...mkavulich:ccpp-physics:feature/ufs_fire_cpl_rebase?expand=1

Apparenly I don't have permission to push to the esmf-org/ccpp-physics repository, so if those changes are correct one of you will have to force-push that branch to this one. Or just open a new PR from a different branch if that's more desirable.

**Comment by masih-e** [comment]
Hi Michael,

Thank you for doing this. It looks good to me. Should we do the RT again?

Masih

**Comment by danrosen25** [comment]
Let's bring this into the existing pull request branch if it's passing the
tests.
https://github.com/esmf-org/ccpp-physics/tree/feature/ufs_fire_cpl

**Comment by mkavulich** [comment]
> Hi Michael, Thank you for doing this. It looks good to me. Should we do the RT again? Masih

I think we should re-run the RTs just to be sure, if that's the last step before opening these PRs for review. Be sure to incorporate this change before running the RTs, since there are some known failures before this point: https://github.com/ufs-community/ufs-weather-model/pull/2362

If you would like help with the RTs just let me know

**Comment by danrosen25** [comment]
@grantfirl @Qingfu-Liu @dustinswales @haiqinli @mkavulich 
Hi all, this is waiting for review.
Thanks, Dan.

**Comment by haiqinli** [comment]
@danrosen25  I and Ravan will review it together, and this may take some time. Thanks.

**Review by grantfirl — APPROVED** [review]
@danrosen25 This looks great to me from a CCPP point of view. Thanks!

**Comment by grantfirl** [comment]
@danrosen25 Have the UFS RTs been run with the latest code for this PR? I'm not seeing any logs with https://github.com/ufs-community/ufs-weather-model/pull/2220/files#diff-57a1b7bb92156b1f8a3167f0ba4d34cf3d320188729bd54157b38b1f31a5d2e2. Please let us know if you'd like us to run them with all of your latest PR code from UFS WM on downward.

**Comment by danrosen25** [comment]
@grantfirl I didn't check logs into the PR for ufs-weather-model. @masih-e and I individually ran the tests. @masih-e ran them in full but I ran them found a bug, fixed it and then finished the remaining. Can you run the regression tests for verification?
https://github.com/ufs-community/ufs-weather-model/pull/2220
https://github.com/esmf-org/ufs-weather-model/tree/feature/ufs_fire_cpl

**Comment by grantfirl** [comment]
> @grantfirl I didn't check logs into the PR for ufs-weather-model. @masih-e and I individually ran the tests. @masih-e ran them in full but I ran them found a bug, fixed it and then finished the remaining. Can you run the regression tests for verification? [ufs-community/ufs-weather-model#2220](https://github.com/ufs-community/ufs-weather-model/pull/2220) https://github.com/esmf-org/ufs-weather-model/tree/feature/ufs_fire_cpl

@danrosen25 Yes, will do. Assuming success, this PR may be scheduled for merging in the next 2 weeks. I'll let you know.

**Review by Qingfu-Liu — APPROVED** [review]

**Comment by grantfirl** [comment]
@danrosen25 Please review/merge in https://github.com/esmf-org/ccpp-physics/pull/1. This updates your PR branch to the latest ufs/dev so that this can be tested by UFS code managers.

**Review by haiqinli — APPROVED** [review]

**Comment by danrosen25** [comment]
@jkbk2004 @grantfirl 
This PR is marked ready because there aren't any submodules that need to be updated. I haven't marked the other PRs because the submodules need to be updated AFTER this PR is merged.

**Comment by zach1221** [comment]
@grantfirl testing is complete on WM [PR-2220](https://github.com/ufs-community/ufs-weather-model/pull/2220), and we're ready to merge this PR.

**Pull request merged**
