### PR TITLE
Add the TEMPO microphysics submodule

### PR DESCRIPTION
**Pull request by AndersJensen-NOAA**
Development of the Thompson-Eidhammer microphysics is transitioning to a submodule, and this submodule is: https://github.com/NCAR/TEMPO

TEMPO stand for Thompson-Eidhammer Microphysics Parameterization for Operations.

The use of a submodule will enable centralized community development (and testing) of the microphysics scheme for various applications and dynamical cores. This submodule will eventually replace the Thompson parameterization currently in the CCPP after approval from all parties involved and significant testing.

This implementation is done in a way that will allow parallel testing of both TEMPO and the original Thompson microphysics.

### CODE REVIEW

**Comment by grantfirl** [comment]
@AndersJensen-NOAA How does this relate to #214? I see that it does everything this does plus some other changes.

**Comment by AndersJensen-NOAA** [comment]
> @AndersJensen-NOAA How does this relate to #214? I see that it does everything this does plus some other changes.

@grantfirl This PR implements TEMPO in parallel to Thompson so they can be tested side-side-side. #214 is an implementation that would replace Thompson. @dustinswales and I decided to do a parallel implementation first.

**Comment by grantfirl** [comment]
Hi @AndersJensen-NOAA, sorry for letting this fester here for a while. Now that our software release is out-the-door, we're trying to catch up on code management tasks. We're trying to prioritize our reviews since there are a few heavy ones. Is this work of particular urgency to get into the UFS merge queue?

**Comment by AndersJensen-NOAA** [comment]
> Hi @AndersJensen-NOAA, sorry for letting this fester here for a while. Now that our software release is out-the-door, we're trying to catch up on code management tasks. We're trying to prioritize our reviews since there are a few heavy ones. Is this work of particular urgency to get into the UFS merge queue?

@grantfirl No worries. We'll need to involve @dustinswales since he has started the process of benchmarking TEMPO versus Thompson. Going forward, the plan is to develop this version of the microphysics with EMC and others and replace Thompson, so the sooner it is in the official repository, the better.

**Comment by dustinswales** [comment]
Closing in favor of #214

**Pull request closed without merging**
