### PR TITLE
Make ozone physics CCPP compliant by removing 'optional' and 'pointer' attributes (includes #168 and #169)

### LINKED ISSUE #165: Erroneous .gitmodules
Hi, I believe this file is incorrect. There should be only one reference to rte-rrtmgp in `.gitmodules`:

https://github.com/ufs-community/ccpp-physics/blob/51452b8b52d5f3ded391847aefc21b086bb27b64/.gitmodules#L1

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

This PR is required to address issues with a recent PR to the physics (https://github.com/ufs-community/ccpp-physics/pull/75) that was not fully CCPP compliant. It introduced Fortran attributes `optional` and `pointer` in the [GFS_suite_stateout_update scheme](https://github.com/ufs-community/ccpp-physics/pull/150/files#diff-ff824ab6afe340ee379b3b664f35cef28b2be4f638401a3779f8ba954210b7a1), both of which are not permitted/supported by the current CCPP framework.

The correct way to handle this situation, as described in the CCPP technical documentation and our recent paper (https://gmd.copernicus.org/articles/16/2235/2023/) is to pass the logical flag that is used in the `active` attribute and read/write from/to the arrays based on that flag.

I will note that we need to address the way we handle inactive data in the near future and that this may or may not require (re-)introducing Fortran attributes thrown out here, but as of now the current code is invalid per CCPP requirements.

I also pulled in #168. and #169 per request from the repository managers. Please see these issues for the description of the respective changes.

## Issues

This PR fixes https://github.com/ufs-community/ccpp-physics/pull/75#issuecomment-1869821166

## Dependencies / associated PRs

This PR is part of a set of PRs that need to be tested and merged together:
- https://github.com/ufs-community/ccpp-physics/pull/150
- https://github.com/NCAR/ccpp-framework/issues/520 (see here for initial regression testing on Hera)
- https://github.com/NOAA-EMC/fv3atm/pull/747
- https://github.com/ufs-community/ufs-weather-model/pull/2066 (see here for final regression testing)

Note that the CI tests fail due to an error unrelated to this PR (related to the CI scripts themselves): https://github.com/ufs-community/ccpp-physics/actions/runs/7334889268/job/19972125491?pr=150

### CODE REVIEW

**Review by dustinswales — CHANGES_REQUESTED** [review]
@climbfuji Thanks for making this change.
My intention was to a) avoid using host logic to control scheme diagnostics, and b) add more flexibility over the diagnostics being requested (e.g output only a subset of the available diagnostics). 
The idea being that if the host allocates (associates) them, the scheme knows to output them. But now that everything will be allocated to at least size(0), this logic doesn't work. We could change "if associated(var)" with "if size(var) > 0" or "if size(var) > 0" ? Thoughts?

**Comment by climbfuji** [comment]
> @climbfuji Thanks for making this change. My intention was to a) avoid using host logic to control scheme diagnostics, and b) add more flexibility over the diagnostics being requested (e.g output only a subset of the available diagnostics). The idea being that if the host allocates (associates) them, the scheme knows to output them. But now that everything will be allocated to at least size(0), this logic doesn't work. We could change "if associated(var)" with "if size(var) > 0" or "if size(var) > 0" ? Thoughts?

Are these changes ready (everything allocated to at least size 0)?

**Comment by dustinswales** [comment]
> > @climbfuji Thanks for making this change. My intention was to a) avoid using host logic to control scheme diagnostics, and b) add more flexibility over the diagnostics being requested (e.g output only a subset of the available diagnostics). The idea being that if the host allocates (associates) them, the scheme knows to output them. But now that everything will be allocated to at least size(0), this logic doesn't work. We could change "if associated(var)" with "if size(var) > 0" or "if size(var) > 0" ? Thoughts?
> 
> Are these changes ready (everything allocated to at least size 0)?

Not yet, but very soon I believe. @grantfirl Can you confirm?

**Comment by grantfirl** [comment]
> > > @climbfuji Thanks for making this change. My intention was to a) avoid using host logic to control scheme diagnostics, and b) add more flexibility over the diagnostics being requested (e.g output only a subset of the available diagnostics). The idea being that if the host allocates (associates) them, the scheme knows to output them. But now that everything will be allocated to at least size(0), this logic doesn't work. We could change "if associated(var)" with "if size(var) > 0" or "if size(var) > 0" ? Thoughts?
> > 
> > 
> > Are these changes ready (everything allocated to at least size 0)?
> 
> Not yet, but very soon I believe. @grantfirl Can you confirm?

Yes, I have code with all conditionally-allocated variables now being allocated to size 0, but I ran into issues before the break with respect to switching variables from pointers to allocatables. GFS_diagnostics is assigning pointers to components of DDTs. This works fine with the DDT components being pointers, and it is apparently supposed to work fine with allocatables as long as the top level DDT (GFS_data_type in this case) is given the TARGET attribute (which it already has), but the compiler is still erring out and I don't really understand why. If we need this ASAP, I can put everything back to pointers that are still being allocated to zero size, but I was going to try to debug why it won't work as TARGET allocatables in GFS_diagnostics.

**Comment by climbfuji** [comment]
> > > > @climbfuji Thanks for making this change. My intention was to a) avoid using host logic to control scheme diagnostics, and b) add more flexibility over the diagnostics being requested (e.g output only a subset of the available diagnostics). The idea being that if the host allocates (associates) them, the scheme knows to output them. But now that everything will be allocated to at least size(0), this logic doesn't work. We could change "if associated(var)" with "if size(var) > 0" or "if size(var) > 0" ? Thoughts?
> > > 
> > > 
> > > Are these changes ready (everything allocated to at least size 0)?
> > 
> > 
> > Not yet, but very soon I believe. @grantfirl Can you confirm?
> 
> Yes, I have code with all conditionally-allocated variables now being allocated to size 0, but I ran into issues before the break with respect to switching variables from pointers to allocatables. GFS_diagnostics is assigning pointers to components of DDTs. This works fine with the DDT components being pointers, and it is apparently supposed to work fine with allocatables as long as the top level DDT (GFS_data_type in this case) is given the TARGET attribute (which it already has), but the compiler is still erring out and I don't really understand why. If we need this ASAP, I can put everything back to pointers that are still being allocated to zero size, but I was going to try to debug why it won't work as TARGET allocatables in GFS_diagnostics.

We can discuss this at our next CCPP framework meeting, but: Even if we add the size-0 allocation, this is only a duct-tape solution so that the code compiles and runs without errors and warnings, as required by NCEP operations.

This does not mean that we should throw overboard the rules and requirements that the CCPP framework developers came up with in the past, which are that conditionally allocated variables must have an active attribute (condition for allocation) in the host model metadata, and schemes must test for that condition in order to access the variable. If we want to change that, then I think we need to take this back to the CCPP framework developer meeting and discuss this in a broader context than just the UFS and NCEP operations. I personally think that we need to take this back to the drawing board and see if we can come up with a better solution altogether. But, for now, this PR is simply applying current CCPP rules and requirements and removing code that violates those rules.

**Comment by dustinswales** [comment]
> > > > > @climbfuji Thanks for making this change. My intention was to a) avoid using host logic to control scheme diagnostics, and b) add more flexibility over the diagnostics being requested (e.g output only a subset of the available diagnostics). The idea being that if the host allocates (associates) them, the scheme knows to output them. But now that everything will be allocated to at least size(0), this logic doesn't work. We could change "if associated(var)" with "if size(var) > 0" or "if size(var) > 0" ? Thoughts?
> > > > 
> > > > 
> > > > Are these changes ready (everything allocated to at least size 0)?
> > > 
> > > 
> > > Not yet, but very soon I believe. @grantfirl Can you confirm?
> > 
> > 
> > Yes, I have code with all conditionally-allocated variables now being allocated to size 0, but I ran into issues before the break with respect to switching variables from pointers to allocatables. GFS_diagnostics is assigning pointers to components of DDTs. This works fine with the DDT components being pointers, and it is apparently supposed to work fine with allocatables as long as the top level DDT (GFS_data_type in this case) is given the TARGET attribute (which it already has), but the compiler is still erring out and I don't really understand why. If we need this ASAP, I can put everything back to pointers that are still being allocated to zero size, but I was going to try to debug why it won't work as TARGET allocatables in GFS_diagnostics.
> 
> We can discuss this at our next CCPP framework meeting, but: Even if we add the size-0 allocation, this is only a duct-tape solution so that the code compiles and runs without errors and warnings, as required by NCEP operations.

There are other solutions that could be applied instead of allocating to size(0):
- Declaring arguments as explicit-shape vs. assumed shape OR
- adding the optional attribute.
would both remove the runtime errors, but they aren't CCPP compliant. Allocating to size(0) is allowable within the CCPP rules, but as you said, and I completely agree, it's just duct-tape to avoid runtime errors.

> 
> This does not mean that we should throw overboard the rules and requirements that the CCPP framework developers came up with in the past, which are that conditionally allocated variables must have an active attribute (condition for allocation) in the host model metadata, and schemes must test for that condition in order to access the variable. If we want to change that, then I think we need to take this back to the CCPP framework developer meeting and discuss this in a broader context than just the UFS and NCEP operations. I personally think that we need to take this back to the drawing board and see if we can come up with a better solution altogether. But, for now, this PR is simply applying current CCPP rules and requirements and removing code that violates those rules.

I agree that this needs further discussion. TBH, I never really understood the spirit of the "active" attribute and I think it should be revisited.

**Comment by climbfuji** [comment]
> > > > > @climbfuji Thanks for making this change. My intention was to a) avoid using host logic to control scheme diagnostics, and b) add more flexibility over the diagnostics being requested (e.g output only a subset of the available diagnostics). The idea being that if the host allocates (associates) them, the scheme knows to output them. But now that everything will be allocated to at least size(0), this logic doesn't work. We could change "if associated(var)" with "if size(var) > 0" or "if size(var) > 0" ? Thoughts?
> > > > 
> > > > 
> > > > Are these changes ready (everything allocated to at least size 0)?
> > > 
> > > 
> > > Not yet, but very soon I believe. @grantfirl Can you confirm?
> > 
> > 
> > Yes, I have code with all conditionally-allocated variables now being allocated to size 0, but I ran into issues before the break with respect to switching variables from pointers to allocatables. GFS_diagnostics is assigning pointers to components of DDTs. This works fine with the DDT components being pointers, and it is apparently supposed to work fine with allocatables as long as the top level DDT (GFS_data_type in this case) is given the TARGET attribute (which it already has), but the compiler is still erring out and I don't really understand why. If we need this ASAP, I can put everything back to pointers that are still being allocated to zero size, but I was going to try to debug why it won't work as TARGET allocatables in GFS_diagnostics.
> 
> We can discuss this at our next CCPP framework meeting, but: Even if we add the size-0 allocation, this is only a duct-tape solution so that the code compiles and runs without errors and warnings, as required by NCEP operations.
> 
> This does not mean that we should throw overboard the rules and requirements that the CCPP framework developers came up with in the past, which are that conditionally allocated variables must have an active attribute (condition for allocation) in the host model metadata, and schemes must test for that condition in order to access the variable. If we want to change that, then I think we need to take this back to the CCPP framework developer meeting and discuss this in a broader context than just the UFS and NCEP operations. I personally think that we need to take this back to the drawing board and see if we can come up with a better solution altogether. But, for now, this PR is simply applying current CCPP rules and requirements and removing code that violates those rules.



> > > > > > @climbfuji Thanks for making this change. My intention was to a) avoid using host logic to control scheme diagnostics, and b) add more flexibility over the diagnostics being requested (e.g output only a subset of the available diagnostics). The idea being that if the host allocates (associates) them, the scheme knows to output them. But now that everything will be allocated to at least size(0), this logic doesn't work. We could change "if associated(var)" with "if size(var) > 0" or "if size(var) > 0" ? Thoughts?
> > > > > 
> > > > > 
> > > > > Are these changes ready (everything allocated to at least size 0)?
> > > > 
> > > > 
> > > > Not yet, but very soon I believe. @grantfirl Can you confirm?
> > > 
> > > 
> > > Yes, I have code with all conditionally-allocated variables now being allocated to size 0, but I ran into issues before the break with respect to switching variables from pointers to allocatables. GFS_diagnostics is assigning pointers to components of DDTs. This works fine with the DDT components being pointers, and it is apparently supposed to work fine with allocatables as long as the top level DDT (GFS_data_type in this case) is given the TARGET attribute (which it already has), but the compiler is still erring out and I don't really understand why. If we need this ASAP, I can put everything back to pointers that are still being allocated to zero size, but I was going to try to debug why it won't work as TARGET allocatables in GFS_diagnostics.
> > 
> > 
> > We can discuss this at our next CCPP framework meeting, but: Even if we add the size-0 allocation, this is only a duct-tape solution so that the code compiles and runs without errors and warnings, as required by NCEP operations.
> 
> There are other solutions that could be applied instead of allocating to size(0):
> 
> * Declaring arguments as explicit-shape vs. assumed shape OR
> * adding the optional attribute.
>   would both remove the runtime errors, but they aren't CCPP compliant. Allocating to size(0) is allowable within the CCPP rules, but as you said, and I completely agree, it's just duct-tape to avoid runtime errors.
> 
> > This does not mean that we should throw overboard the rules and requirements that the CCPP framework developers came up with in the past, which are that conditionally allocated variables must have an active attribute (condition for allocation) in the host model metadata, and schemes must test for that condition in order to access the variable. If we want to change that, then I think we need to take this back to the CCPP framework developer meeting and discuss this in a broader context than just the UFS and NCEP operations. I personally think that we need to take this back to the drawing board and see if we can come up with a better solution altogether. But, for now, this PR is simply applying current CCPP rules and requirements and removing code that violates those rules.
> 
> I agree that this needs further discussion. TBH, I never really understood the spirit of the "active" attribute and I think it should be revisited.

I agree!

**Review by dustinswales — APPROVED** [review]

**Review by Qingfu-Liu — APPROVED** [review]

**Review by grantfirl — APPROVED** [review]

**Review by mzhangw — APPROVED** [review]

**Comment by grantfirl** [comment]
@climbfuji Could you pull in #169? I've run RTs separately on it, and those changes also don't affect baselines. That way, we'll merge 3 PRs in one go.

**Comment by climbfuji** [comment]
@grantfirl done. I also updated my set of PRs from the authoritative repositories and pushed the changes to all PRs.

**Comment by zach1221** [comment]
@grantfirl testing is complete on ufs-wm PR #2066. Can you please merge this PR?
fyi @climbfuji

**Comment by grantfirl** [comment]
@dustinswales @climbfuji Thanks for merging, Dustin -- beat me to it. I'm glad to get these changes in finally.

**Pull request merged**
