### PR TITLE
Bug fix for physics suites using C3 or SAS convection with MYNN PBL scheme

### PR DESCRIPTION
**Pull request by lisa-bengtsson**
Issue: https://github.com/ufs-community/ufs-weather-model/issues/2342

When running physics suites using C3 or SAS convection with the prognostic area fraction closure, and MYNN PBL, there is a bug in that the convection expects the field "tendency_of_vertically_diffused_tracer_concentration", to compute the turbulent moisture flux component of the total moisture convergence term, that is output from all PBL schemes except MYNN.

This PR adds "tendency_of_vertically_diffused_tracer_concentration" as output from the MYNN PBL scheme.

### CODE REVIEW

**Review by joeolson42 — APPROVED** [review]

**Comment by grantfirl** [comment]
@lisa-bengtsson For suites using MYNN PBL, I see that GFS_PBL_generic_post is bypassed (where the `dvdftra` array is copied back to individual terms in the `dqdt` or (process_split_cumulative_tendency_of_tracers) array). Rather than modify the MYNN scheme to output the needed tendency_of_vertically_diffused_tracer_concentration array, why don't the convective schemes use the process_split_cumulative_tendency_of_specific_humidity variable directly? It looks like C3 is only really after that slice of the larger array anyway.

**Comment by lisa-bengtsson** [comment]
> @lisa-bengtsson For suites using MYNN PBL, I see that GFS_PBL_generic_post is bypassed (where the `dvdftra` array is copied back to individual terms in the `dqdt` or (process_split_cumulative_tendency_of_tracers) array). Rather than modify the MYNN scheme to output the needed tendency_of_vertically_diffused_tracer_concentration array, why don't the convective schemes use the process_split_cumulative_tendency_of_specific_humidity variable directly? It looks like C3 is only really after that slice of the larger array anyway.

@grantfirl I don't want to cumulative tendency, I only want the tendency due to PBL processes.

**Review by grantfirl — APPROVED** [review]

**Comment by grantfirl** [comment]
@lisa-bengtsson I'm thinking of combining this with https://github.com/ufs-community/ccpp-physics/pull/213 to expedite testing/merging. Is that OK with you?

**Review by Qingfu-Liu — APPROVED** [review]

**Review by dustinswales — APPROVED** [review]

**Review by climbfuji — APPROVED** [review]

**Comment by grantfirl** [comment]
@lisa-bengtsson Combined into https://github.com/ufs-community/ccpp-physics/pull/223 (Scheduled for UFS merge queue early next week)

**Pull request closed without merging**
