### PR TITLE
[production/RRFS.v1] update deep soil temperature of RUC LSM

### PR DESCRIPTION
**Pull request by haiqinli**
Update the RUC LSM deep soil temperature from climatology to real forecast.

### CODE REVIEW

**Review by grantfirl — APPROVED** [review]

**Comment by grantfirl** [comment]
@haiqinli Is there a good reason to not include these changes in https://github.com/ufs-community/ccpp-physics/pull/211?

**Comment by haiqinli** [comment]
> @haiqinli Is there a good reason to not include these changes in #211?
@grantfirl Per our discussion with Ming and Curtis, we will split the PR #211 into two seperate PRs. The new PR #217 only includes the FMS and minor RUC LSM deep soil temperature updates, and this new PR could be merged into RRFS.v1 easily. The smoke updates will be kept in the original PR #211. However, we need to do some retro runs to guarantee there will be very minor impacts on the meteorology forecast, and may take more time. Thanks.

**Comment by grantfirl** [comment]
> > @haiqinli Is there a good reason to not include these changes in #211?
> > @grantfirl Per our discussion with Ming and Curtis, we will split the PR #211 into two seperate PRs. The new PR #217 only includes the FMS and minor RUC LSM deep soil temperature updates, and this new PR could be merged into RRFS.v1 easily. The smoke updates will be kept in the original PR #211. However, we need to do some retro runs to guarantee there will be very minor impacts on the meteorology forecast, and may take more time. Thanks.

OK, sounds good. Thanks for the clarification.

**Comment by jkbk2004** [comment]
Tests all completed at https://github.com/ufs-community/ufs-weather-model/pull/2343. @grantfirl @dustinswales You can go ahead to merge this pr.

**Pull request merged**
