### PR TITLE
Combo for #41 and #45

### PR DESCRIPTION
**Pull request by grantfirl**
This combines work from @climbfuji: #41 and @Jili-Dong : #45 

This updates CMakeLists.txt to require the sp library and adds 3 input parameters for the NSSL MP scheme. No baseline changes are expected for either change.

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]
Thanks @grantfirl !

**Comment by Jili-Dong** [comment]
thanks @grantfirl !

**Comment by grantfirl** [comment]
@dustinswales Please review this when you get a chance. It just combines #41 and #45.

**Review by dustinswales — APPROVED** [review]
@grantfirl Thanks for combining these!

**Pull request merged**
