### PR TITLE
 z0t bug fixes

### PR DESCRIPTION
**Pull request by HelinWei-NOAA**
To fix two bugs related to the thermal roughness raised in issues 963 and 964.

[The presentation
](https://docs.google.com/presentation/d/1DQhOVEtvB2fz4JB4IHZlDVrysMy7UapHb_QaRHMoh70/edit#slide=id.gfef90e96fe_0_78) shows the impact of the bug mentioned in https://github.com/NCAR/ccpp-physics/issues/964
[Another presentation
](https://docs.google.com/presentation/d/1ZDTUwtw9s_KSqtcP64vqJ_bOOD4figDF/edit#slide=id.p1) addresses the impact of both bugs.

### CODE REVIEW

**Comment by HelinWei-NOAA** [comment]
https://github.com/NCAR/ccpp-physics/issues/963

**Comment by HelinWei-NOAA** [comment]
https://github.com/NCAR/ccpp-physics/issues/964[
](https://github.com/NCAR/ccpp-physics/issues/964)

**Comment by HelinWei-NOAA** [comment]
https://github.com/NCAR/ccpp-physics/issues/964

**Review by ChunxiZhang-NOAA — APPROVED** [review]
Looks good.

**Comment by ChunxiZhang-NOAA** [comment]
@HelinWei-NOAA  You you have a PPT file to show how those bug fixes improve the forecasts, please attach it in the description section for this PR.

**Comment by ChunxiZhang-NOAA** [comment]
@HelinWei-NOAA Please create a corresponding fv3atm PR and ufs-weather-model PR, respectively.

**Comment by HelinWei-NOAA** [comment]
@ChunxiZhang-NOAA  We don't have any modification for those two repositories. I can create those PRs if you want to commit our ccpp-physics changes separately.

> @HelinWei-NOAA Please create a corresponding fv3atm PR and ufs-weather-model PR, respectively.

**Comment by HelinWei-NOAA** [comment]
done
> @HelinWei-NOAA You you have a PPT file to show how those bug fixes improve the forecasts, please attach it in the description section for this PR.

**Comment by ChunxiZhang-NOAA** [comment]
> @ChunxiZhang-NOAA We don't have any modification for those two repositories. I can create those PRs if you want to commit our ccpp-physics changes separately.
> 
> > @HelinWei-NOAA Please create a corresponding fv3atm PR and ufs-weather-model PR, respectively.

@HelinWei-NOAA Those two upstream PRs are needed even though no code changes in fv3atm and ufs-weather-model. I can create those two PRs for you.

**Comment by HelinWei-NOAA** [comment]
@ChunxiZhang-NOAA I though you would combine our bug fixes with other physics upgrades. Thanks for creating those two PRs for us.
> @HelinWei-NOAA Those two upstream PRs are needed even though no code changes in fv3atm and ufs-weather-model. I can create those two PRs for you.

**Comment by ChunxiZhang-NOAA** [comment]
@HelinWei-NOAA Could you make your baseline.hr1 branch update-to-date with following method: assuming you have remote  set to origin: https://github.com/HelinWei-NOAA/ccpp-physics and upstream: https://github.com/ufs-community/ccpp-physics; and you are in your baseline.hr1 branch. You can try:  git fetch upstream, then git merge upstream/ufs/dev

**Comment by HelinWei-NOAA** [comment]
Done. Thanks for the instruction.

**Comment by ChunxiZhang-NOAA** [comment]
@HelinWei-NOAA My pleasure. The ufs-weather-model PR[#1493](https://github.com/ufs-community/ufs-weather-model/pull/1493) and fv3atm PR[#610](https://github.com/NOAA-EMC/fv3atm/pull/601) were created.

**Review by grantfirl — APPROVED** [review]

**Review by dustinswales — APPROVED** [review]

**Comment by ChunxiZhang-NOAA** [comment]
@HelinWei-NOAA Could you merge your baseline.hr1 branch with the official repository to make it up-to-date once more? A few new commits have been merged into ufs/dev branch since your last update. Thanks.

**Comment by HelinWei-NOAA** [comment]
Done.
> @HelinWei-NOAA Could you merge your baseline.hr1 branch with the official repository to make it up-to-date once more? A few new commits have been merged into ufs/dev branch since your last update. Thanks.

**Comment by ChunxiZhang-NOAA** [comment]
> Done.
> 
> > @HelinWei-NOAA Could you merge your baseline.hr1 branch with the official repository to make it up-to-date once more? A few new commits have been merged into ufs/dev branch since your last update. Thanks.

@HelinWei-NOAA Thank you!

**Comment by jkbk2004** [comment]
All tests are done on https://github.com/ufs-community/ufs-weather-model/pull/1493 side. Can we start merging in this pr?

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 Done.

**Pull request merged**
