### PR TITLE
Fix .gitmodule bug

### PR DESCRIPTION
**Pull request by dustinswales**

### CODE REVIEW

**Review by Qingfu-Liu — APPROVED** [review]

**Review by climbfuji — APPROVED** [review]

**Comment by climbfuji** [comment]
Resolves #165

**Review by mkavulich — APPROVED** [review]

**Comment by grantfirl** [comment]
@dustinswales @mkavulich @climbfuji Let's combine this with https://github.com/ufs-community/ccpp-physics/pull/150, which may also be combined with #149. None of them change baselines.

**Comment by grantfirl** [comment]
> @dustinswales @mkavulich @climbfuji Let's combine this with #150, which may also be combined with #149. None of them change baselines.

@climbfuji If you are OK with this strategy, would you pull this PR into your branch for #150, please?

**Comment by dustinswales** [comment]
Thanks @climbfuji for cleaning up my many messes!

**Comment by climbfuji** [comment]
> > @dustinswales @mkavulich @climbfuji Let's combine this with #150, which may also be combined with #149. None of them change baselines.
> 
> @climbfuji If you are OK with this strategy, would you pull this PR into your branch for #150, please?

Ok, let me do that

**Comment by climbfuji** [comment]
done

**Review by mzhangw — APPROVED** [review]

**Pull request merged**
