### PR TITLE
Fixed instability in upper atmosphere due to OGWD

### LINKED ISSUE #95: Adding tendency limiter for mesosphere and horizontal wave number filter for orographic gravity wave drag in UGWP
## Description
1)  The orographic gravity wave drag (OGWD) component of the unified gravity wave physics (UGWP) suite of parameterizations can cause model crashes due to excessive wind tendencies.  These crashes occur at high altitudes, typically in the mesosphere, where the rarified air density causes parameterized waves to (physically) significantly increase in amplitude.   (See slide 1 in pdf attachment below.)  These crashes can be remedied by taking a much smaller time step, but this is not practical.
2)  The zonally averaged surface OGWD stress is excessive in the southern hemisphere, in association with the Andes mountain range.  (See slide 3 in pdf attachment below.)  The near-surface winds are frequently very strong in these regions, and the OGWD scheme does not limit the OGWD stress when wind speed reaches a point where the waves become evanescent and do not impart a drag force.

## Solution
1)  Model crashes in the upper levels of the model can be avoided by limiting the velocity tendency due to OGWD such that in one time step, the winds can not reach zero (or reverse sign).  Proposed code for the fix above the pressure level "plolevmeso", which we've tested at 0.7mb (roughly the height of the stratopause) is shown in slide 2 of the attached pdf.  Model crashes are avoided with the proposed tendency limiter.
2)  From linear theory, if the ratio of the static stability (N) to the wind speed (U) is less than the horizontal wave number of the topography (k_s), that is if N/U < k_s, then orographic gravity waves do not vertically propagate and their wave stress is zero.  We've added code to the OGWD component to take this into effect, where we set k_s from the minimum sub-grid topographic wavelength expected from a grid size of dx.  We consider the assumed maximum sub-grid wavelength to be 0.5*dx.

[CCPP_Issue_slides_2023_08_04.pdf](https://github.com/ufs-community/ccpp-physics/files/12265315/CCPP_Issue_slides_2023_08_04.pdf)

### PR DESCRIPTION
**Pull request by mdtoyNOAA**
This PR fixes [Issue #95](https://github.com/ufs-community/ccpp-physics/issues/95), which involved a stability issue in the upper atmosphere due to the orographic gravity wave drag (OGWD) scheme and also limits the surface OGWD stress in regions of high surface winds (and/or low near-surface static stability) in which internal gravity waves should not develop.

### CODE REVIEW

**Review by Qingfu-Liu — APPROVED** [review]

**Review by dustinswales — APPROVED** [review]
@mdtoyNOAA The changes look good to me. Thanks!

**Review by grantfirl — APPROVED** [review]

**Comment by jkbk2004** [comment]
@mdtoyNOAA can you combine in code change from #115 to this PR?

**Comment by mdtoyNOAA** [comment]
> @mdtoyNOAA can you combine in code change from #115 to this PR?

@jkbk2004 Sure I can do that.  Just to make sure, would I pull Helin's 'hr3_land_upgrades' branch from the fork https://github.com/HelinWei-NOAA/ccpp-physics/tree/hr3_land_upgrades into my branch?  Also, would I need to run RT's right away, or can I wait until Monday, 10/16 when it's my turn to merge the ufs-weather-model [PR#1923](https://github.com/ufs-community/ufs-weather-model/pull/1923)?

**Comment by barlage** [comment]
@mdtoyNOAA can you merge the hr3_land_upgrades branch again? @HelinWei-NOAA just pushed a final commit to that branch.

**Comment by mdtoyNOAA** [comment]
> @mdtoyNOAA can you merge the hr3_land_upgrades branch again? @HelinWei-NOAA just pushed a final commit to that branch.

@barlage Yes, I can do that, but first I'd like to confirm that I should not merge Anning's PR#109 before doing that.  Or does it matter?

**Comment by mdtoyNOAA** [comment]
@barlage I merged the new hr3_land_upgrades branch.

**Comment by zach1221** [comment]
@grantfirl testing is complete on ufs-wm PR [#1923](https://github.com/ufs-community/ufs-weather-model/pull/1923), can you merge this PR for us, please?

**Pull request merged**
