### PR TITLE
Rollback changes to rain evaporation

### PR DESCRIPTION
**Pull request by AndersJensen-NOAA**

### CODE REVIEW

**Review by dustinswales — APPROVED** [review]
@gthompsnWRF It's generally best to avoid creating branches on the authoritative repos, mostly to keep it lean, but also to avoid cases like this where code managers have to approve PRs into your working code base.

**Comment by grantfirl** [comment]
@AndersJensen-NOAA Can we make this change in #69 instead of making this its own PR? It's a little strange to have a PR (that hasn't been merged yet) to create a change and simultaneously have another to undo part of it.

**Comment by dustinswales** [comment]
> @AndersJensen-NOAA Can we make this change in #69 instead of making this its own PR? It's a little strange to have a PR (that hasn't been merged yet) to create a change and simultaneously have another to undo part of it.

@grantfirl I think the problem is not that @AndersJensen-NOAA  is trying to push to @gthompsnWRF's branch, but that Greg's branch is on the ufs-community fork, not his personal fork...

**Comment by grantfirl** [comment]
> > @AndersJensen-NOAA Can we make this change in #69 instead of making this its own PR? It's a little strange to have a PR (that hasn't been merged yet) to create a change and simultaneously have another to undo part of it.
> 
> @grantfirl I think the problem is not that @AndersJensen-NOAA is trying to push to @gthompsnWRF's branch, but that Greg's branch is on the ufs-community fork, not his personal fork...

Oh, I see. I didn't look at the PR target. @AndersJensen-NOAA please disregard. In this case, I think that we should just merge it in. Any objections?

**Pull request merged**
