### PR TITLE
Introduce namelist flag xr_cnvcld to control if suspended grid-mean convective cloud condensate should be included in cloud fraction and optical depth calculation in the GFS suite

### PR DESCRIPTION
**Pull request by lisa-bengtsson**
This PR introduces namelist flag xr_cnvcld to control if suspended grid-mean convective cloud condensate should be included in cloud fraction and optical depth calculation in radiation in the GFS suite.

The default setting is .true. so all regression tests passes (on Hera). We recommend using .false. for C96 resolution. 

Background:
Shan Sun, at GSL found the coupled SFS simulations (HR3 tag) at C96 have a drift in SST, not seen in C192 or C384. And not seen in P8 tag at C96 resolution. 

I proposed that it is likely related to the cloud/convection/radiation interaction introduced in HR1 causing a feedback loop at when grid-mean suspended convective clouds are added to the cloud fraction at coarse resolution. Sensitivity tests showed that is the case. In discussion with Jongil Han, Ruiyu Sun and Fanglin Yang, EMC we propose to add a namelist flag that can be used for tuning at different applications (resolutions)

From Shan Sun, GSL: 
image

### CODE REVIEW

**Review by dustinswales — APPROVED** [review]
@lisa-bengtsson These changes all look fine.
One comment though, [there is already a flag to do this in RRTMGP](https://github.com/NOAA-EMC/fv3atm/blob/develop/ccpp/data/GFS_typedefs.F90#L899), which you could use on the fv3atm side instead of introducing a new one for RRTMG. We could generalize it to doRAD_sgs_cnv, or something along those lines?

**Review by RuiyuSun — APPROVED** [review]

**Review by JongilHan66 — APPROVED** [review]

**Comment by lisa-bengtsson** [comment]
@dustinswales sure, I can use doRAD_sgs_cnv. Is it used in any other routine that could cause some conflict, e.g. if we tested MYNN in GFS or such? Is it default .true.? Otherwise I will have to set it to .true. in a bunch of RT's using this GFS suite.

**Comment by dustinswales** [comment]
@lisa-bengtsson It's not used outside of GP, so there shouldn't be any conflict using it within RRTMG.

**Comment by lisa-bengtsson** [comment]
It looks like doGP_sgs_cnv is default .false. so I would have to update all the RT's where this needs to be .true., and also rename it to doRAD_sgs_cnv everywhere in the code?

**Comment by dustinswales** [comment]
@lisa-bengtsson Just go ahead with your new nml option. I will follow up with this in a subsequent PR.

**Review by Qingfu-Liu — APPROVED** [review]

**Review by grantfirl — APPROVED** [review]

**Comment by zach1221** [comment]
@grantfirl testing is complete on UFS-WM PR #2202. Please feel free to merge this ccpp-physics sub-PR.

**Pull request merged**
