### PR TITLE
fixed excessive evaporation when both innerloop=T and mraerosol=T

### PR DESCRIPTION
**Pull request by AnningCheng-NOAA**
One line of code modification fixing the excessive evaporation problem when both Innerloop and mraerosol is T

### CODE REVIEW

**Comment by dustinswales** [comment]
@AndersJensen-NOAA

**Review by dustinswales — APPROVED** [review]

**Review by Qingfu-Liu — APPROVED** [review]

**Comment by lisa-bengtsson** [comment]
@joeolson42 @AndersJensen-NOAA this could be related to some of the issues we discussed.

**Comment by AndersJensen-NOAA** [comment]
> One line of code modification fixing the excessive evaporation problem when both Innerloop and mraerosol is T

@AnningCheng-NOAA Can we get more details on the excessive evaporation problem?

**Comment by AnningCheng-NOAA** [comment]
Sure.

**Comment by lisa-bengtsson** [comment]
Hi Anning, I would be interested in more info as well, is it related to the inner loop? With the aerosol aware Thompson, we found quite large sensitivity to the choice of dt_inner in the amount of precipitation generated, that we don't see in the non-aerosol aware version. I wonder if what you have found here could be related?

**Comment by yangfanglin** [comment]
@lisa-bengtsson @AndersJensen-NOAA  Anning found the issue when he ran the aerosol-aware version of Thompson MP with MERRA2 aerosol climatology.   I know you are using "prognostic" aerosols so the question might be different.  You can test by removing inner loop but with a shorter dt_atmos (for stability) and  then compare it to your control with dt inner.   If there is large change in column integrated cloud water, then you are having the same issue.  

Anning, please provide more details if you have

**Comment by AnningCheng-NOAA** [comment]
Agree with Fanglin. The results from the run with Innerloop should not be much different from the run without Innerloop and with the same time step as the inner loop used. We discussed the issue with Ruiyu and tends for a more sophisticate aerosol evaporation, but ends up with a simple solutions proposed here.
The evaporation approach does not make much difference (attached figure) on the global mean surface precipitation, likely due to the self contraint of GFS. 
prcp_3p_evap

**Comment by AndersJensen-NOAA** [comment]
@AnningCheng-NOAA and @yangfanglin Thank you for the information and the plots.
Do I understand correctly that you are comping runs with: 1) an inner-loop, for example, 2 calls to the microphysics with each call being 75 seconds (with dt_atmos=150 seconds for example), versus 1 call to everything including microphysics,  dt_atmos=75 seconds?

How is the evaporation tendency for nc calculated when using merra2_aerosol_aware = .true. after this update?

**Comment by AnningCheng-NOAA** [comment]
@AndersJensen-NOAA yes. This how the results from panel A and B are obtained.  The evaporation is calculated without the influence of NWFA and NIFA, i.e., evaporate liquid or ice until the environment is saturated.

**Comment by AndersJensen-NOAA** [comment]
> @AndersJensen-NOAA yes. This how the results from panel A and B are obtained. The evaporation is calculated without the influence of NWFA and NIFA, i.e., evaporate liquid or ice until the environment is saturated.

Thanks, @AnningCheng-NOAA , but what about nc?

**Review by grantfirl — APPROVED** [review]

**Comment by AnningCheng-NOAA** [comment]
@AndersJensen-NOAA here are the two lines of code without influence of NWFA and NIFA, but do modify nc and ql:
3639            prw_vcd(k) = -rc(k)*orho*odt
3640            pnc_wcd(k) = -nc(k)*orho*odt
Noticed that NIFA and NWFA are determined by aerosol only using the MERRA2 climatology approach, not the same as the NIFA and NWFA forecasting approaches (aerosol_aware =T).

**Comment by AnningCheng-NOAA** [comment]
One more thing, when gocart is turned on, mraerosol need to be true in order to coupled with Thompson microphysics. In this case, "is_aerosol_aware" option needs to be False. It is kind of awkward due to the reservation of "is_aerosol_aware" by NIFA and NWFA forecasting approach.

**Comment by AndersJensen-NOAA** [comment]
@AnningCheng-NOAA 
This part of the code is a bit confusing, but here's the logic:
```
do k = kts, kte ! Main k loop
   if ( (ssatw(k).gt. eps) .or. (ssatw(k).lt. -eps .and. L_qc(k)) ) then ! Check for sub- or super-saturation
      if (xrc.gt. R1) then ! Check for cloud water above the R1 limit
         if (clap .gt. eps) then ! Nucleation
         elseif (clap .lt. -eps .AND. ssatw(k).lt.-1.E-6 .AND. (is_aerosol_aware .or. merra2_aerosol_aware)) then  ! Evaporation
         endif ! endif for Nucleation/Evaporation
      else ! Else for cloud water check
         prw_vcd(k) = -rc(k)*orho*odt
         pnc_wcd(k) = -nc(k)*orho*odt
      endif ! endif for cloud water check (xrc > R1)
   endif ! line 3667 endif for sub- or super-saturation check and liquid present
enddo ! line 3668
```

I think the part of the code you are referring to is the "clean-up" where all cloud water mass and number is evaporated if xrc is not greater than R1.

**Comment by AnningCheng-NOAA** [comment]
@AndersJensen-NOAA Yes. The evaporation occurs only when xrc< R1.  We might need a more sophisticated one in the future although using this one as a starting point is good at this moment. When fixing the NIFA and NWFA, I have testing some schemes at hand, not satisfied as this one  so far.

**Comment by zach1221** [comment]
@grantfirl testing is finished on WM PR #2221. Can you please merge is PR?

**Pull request merged**
