### PR TITLE
Add missing dependency on libsp to top-level CMakeLists.txt

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

ccpp-physics depends on `libsp`, but this dependency is not explicitly spelled out in `CMakeLists.txt`.

This PR is required for https://github.com/JCSDA/ufs-bundle/issues/19

### CODE REVIEW

**Comment by climbfuji** [comment]
@ChunxiZhang-NOAA @grantfirl I think this is a pretty safe and tiny PR that can be combined with any other PRs. Thanks in advance for your help!

**Review by grantfirl — APPROVED** [review]

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by dustinswales** [comment]
@grantfirl @ChunxiZhang-NOAA 
Should we combine this with [38](https://github.com/ufs-community/ccpp-physics/pull/38)?

**Comment by arunchawla-NOAA** [comment]
why does CCPP have a dependency on the spectral library?

**Comment by grantfirl** [comment]
> @grantfirl @ChunxiZhang-NOAA Should we combine this with [38](https://github.com/ufs-community/ccpp-physics/pull/38)?

We could. The only reason I hesitated was because it should be able to go into any fv3atm PR and this PR is already pretty big.

**Comment by dustinswales** [comment]
> > @grantfirl @ChunxiZhang-NOAA Should we combine this with [38](https://github.com/ufs-community/ccpp-physics/pull/38)?
> 
> We could. The only reason I hesitated was because it should be able to go into any fv3atm PR and this PR is already pretty big.

Makes sense. Lets wait

**Comment by grantfirl** [comment]
> why does CCPP have a dependency on the spectral library?

@arunchawla-NOAA I can't recall, but I'll look. @climbfuji Do you recall off the top of your head?

**Comment by climbfuji** [comment]
code in sfcsub.F : grid transforms (ga2la etc)

We talked a long time ago about moving this one or two subroutines that are needed into the ccpp-physics repo / sfcsub.F code, but that is again duplication. May still be worth doing.

**Comment by grantfirl** [comment]
@climbfuji Beat me to it. I just found the calls to splat in sfcsub.F.

**Comment by arunchawla-NOAA** [comment]
In general I am not a fan of code duplication, but if we are moving away from spectral libraries then I do not see the need for carrying these libraries around just for a couple of routines. If there are some good ideas we can talk with the libraries team

**Comment by dustinswales** [comment]
@grantfirl @climbfuji What about adding the [splib](https://github.com/NOAA-EMC/NCEPLIBS-sp/tree/develop/src) as an external to the physics? (maybe checkout to something like /physics/externals_tools/splib?) And modifying the dependent files to use these directly.

**Comment by climbfuji** [comment]
It’s an overkill, the total number of lines we need from libsp is probably around 100

**Comment by grantfirl** [comment]
Ya, I just looked, it's closer to 300 lines with comments, but it is all contained in splat.F and lapack_gen.F in https://github.com/NOAA-EMC/NCEPLIBS-sp

**Comment by grantfirl** [comment]
lapack_gen.F contains code from Numerical Recipes for matrix inversion. splat.F does 
`Computes cosines of colatitude and Gaussian weights for sets of latitudes`.

One could also question whether gcycle (which is where these dependencies originate) should be called within CCPP.

**Comment by arunchawla-NOAA** [comment]
lapack is a generic routine from numerical recipes and splat is specific for computing values for a gaussian grid. You need that in CCPP? In either case I think these are routines that are not really changing

**Comment by grantfirl** [comment]
@arunchawla-NOAA @climbfuji @dustinswales I started an issue to continue this discussion.

@arunchawla-NOAA It looks like there is a stronger dependency of several schemes on the w3emc library (which has bacio as a sub-dependency). In your opinion, is it also important to try to remove this dependency, or is the sp dependency particularly egregious because GFS is no longer spectral?

**Comment by grantfirl** [comment]
I suggest that we continue with merging this PR until we have the long-term solution in order not to hold up JEDI work.

**Comment by arunchawla-NOAA** [comment]
That is fine with me. Long term it will be good to understand why all this dependencies on spectral libraries if the model is no longer spectral

**Review by dustinswales — APPROVED** [review]

**Comment by grantfirl** [comment]
This change was merged into #53

**Pull request closed without merging**
