### PR TITLE
Changed UGWP diagnostic variable declaration intents from 'out' to 'inout'

### LINKED ISSUE #37: Possible correction to declaration intent for diagnostic variables in drag_suite.F90
# Description

The UGWP diagnostic variables listed below are declared with "intent(out)" in unified_ugwp.F90 (subroutine "unified_ugwp_run") and are initialized in the same subroutine.  These variables are then passed to subroutine "drag_suite_run".  In subroutine "drag_suite_run" (in drag_suite.F90), these variables are declared with "intent(out)", and then calculations are performed on most of the grid points.  If a grid point is skipped (mainly ocean points), then the initialized value holds.  Because of this, I believe the variables should be declared with "intent(inout)" instead of "intent(out)" in "drag_suite_run".

List of effected diagnostic variables:
dusfc_ms(:),dvsfc_ms(:), dusfc_bl(:),dvsfc_bl(:), dusfc_ss(:),dvsfc_ss(:), dusfc_fd(:),dvsfc_fd(:)
dtaux2d_ms(:,:),dtauy2d_ms(:,:),  dtaux2d_bl(:,:),dtauy2d_bl(:,:),dtaux2d_ss(:,:),dtauy2d_ss(:,:), dtaux2d_fd(:,:),dtauy2d_fd(:,:), 

## Steps to Reproduce

This "bug" does not appear to be causing any issues.  I changed the declaration in drag_suite.F90 from intent "out" to "inout", and there was no change in the results.  I'm not a computer scientist, but I believe the correct way is to declare the variables in drag_suite.F90 as "inout", since they come in to the subroutine already initialized.

Please let me know if this should indeed be changed and I can issue a PR with this minor change.

## Additional Context

* Machine:  Hera
* Compiler:  Intel
* Suite Definition File or Scheme: unified_ugwp

## Output

N/A

### PR DESCRIPTION
**Pull request by mdtoyNOAA**
This pull request fixes [Issue #37](https://github.com/ufs-community/ccpp-physics/issues/37).  The UGWP diagnostic variables (i.e., dusfc_ms, dvsfc_ms, tdaux2d_ms, datauy2d_ms, etc.) are declared with "intent(out)" and initialized in module unified_ugwp.F90, then they are passed to subroutine "drag_suite_run" (in drag_suite.F90).  In this subroutine, the UGWP diagnostic variables should have been declared with "intent(inout)" instead of "intent(out)".  This PR fixes this.

### CODE REVIEW

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by mdtoyNOAA** [comment]
@ChunxiZhang-NOAA  I forgot to change the "intent" settings for the UGWP diagnostic variables in "drag_suite.meta".  I've just changed them from "out" to "inout" to correspond to the changes in "drag_suite.F90".  I'm about to push this new commit to my branch.

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by ChunxiZhang-NOAA** [comment]
@mdtoyNOAA Because those are diagnostic variables, the bug fixes will not change model results, right?

**Comment by mdtoyNOAA** [comment]
@ChunxiZhang-NOAA  That is correct.

**Comment by ChunxiZhang-NOAA** [comment]
@mdtoyNOAA Good to know, thanks.

**Review by dustinswales — APPROVED** [review]
@mdtoyNOAA Looks good!

**Review by grantfirl — APPROVED** [review]

**Comment by jkbk2004** [comment]
ufs-wm test is done: https://github.com/ufs-community/ufs-weather-model/pull/1597. @ChunxiZhang-NOAA can you merge the pr?

**Comment by BrianCurtis-NOAA** [comment]
Maybe @grantfirl can merge if @ChunxiZhang-NOAA is not available?

**Comment by jkbk2004** [comment]
if @ChunxiZhang-NOAA is not available, @grantfirl can you merge this pr?

**Pull request merged**
