### PR TITLE
Remove warnings from CCPP physics

### PR DESCRIPTION
**Pull request by Qingfu-Liu**
Most credit to @scrasmussen. @Qingfu-Liu removed some unneeded variables.

## Description of Changes: 
Changes to get rid of all the warnings, as pointed out in ufs-weather-model [Issue#1984](https://github.com/ufs-community/ufs-weather-model/issues/1984#issuecomment-1799297076). The fixes for the second and third bullet points were intuited from how similar variables are treated in the code base, if different behavior is preferred please let me know!

- For all the `warning #5462: Global name too long, shortened from` warnings: this issue may be already fixed by the Intel compiler, per [their message board](https://community.intel.com/t5/Intel-Fortran-Compiler/Many-quot-Global-name-too-long-quot-warnings/m-p/1512136/highlight/true#M167584). I haven't had access to the newer Intel 2024.0.1 or 2024.0.2 versions to test.

- The `drain_cpl` and `dsnow_cpl` warnings were "explicit INTENT(OUT) declaration is not given an explicit value". These variables are changed from intent(out) to intent(in) variables. This is to replicate the [rain_cpl and snow_cpl variables](https://github.com/scrasmussen/ccpp-physics/blob/8414f780d1d327a81e95c0e479c3c3ceb9f300bc/physics/GFS_surface_generic_pre.F90#L92-L93).

- The `err_message` return value of two functions were not defined. The error message is defined as "" and if an error occurs in the `open` and `write` statements it will return the error message. Note: this doesn't have the additional `errflg`, as stated in the [coding rules](https://ccpp-techdoc.readthedocs.io/en/latest/CompliantPhysicsParams.html#coding-rules), figure that would be an issue for a different PR if we want it fixed?

- The last remaining warning message still needs to be fixed. It is `FV3/ccpp/physics/physics/dcyc2t3.f(184): warning #6843: A dummy argument with an explicit INTENT(OUT) declaration is not given an explicit value.   [ADJSFCULW]`. This is only used in [a print statement](https://github.com/ufs-community/ccpp-physics/blob/0cdfc9d7465358debb4de292861fef970b44874a/physics/dcyc2t3.f#L353-L356); removed [ADJSFCULW]

## Tests Conducted: 
Testing on Derecho with Intel Fortran 2023.2.1. Result of testing is as follows: 
- Builds without the warnings described as fixed by this PR. Only seeing "Global name too long" and "ADJSFCULW not given an explicit value" warnings. 
- NOTE: Derecho CMake is doing the final linking step to the ESMF and Parallel IO libraries incorrectly. When I manually run the linking command with the correct paths to those libraries, it links correctly.
- Working on getting the [regression test script](https://ufs-weather-model.readthedocs.io/en/latest/BuildingAndRunning.html#using-the-regression-test-script) running but since it does its own build step first, it isn't working due to the linking issue in the previous bullet point. Will add a comment once the regression test script are running properly.

## Dependencies:
None

## Documentation:
No changes.

## Issue (optional): 
Fixes most issues mentioned in ufs-weather-model [Issue#1984](https://github.com/ufs-community/ufs-weather-model/issues/1984#issuecomment-1799297076).

### CODE REVIEW

**Comment by junwang-noaa** [comment]
@Qingfu-Liu would you please create a UFS WM PR for this? 
@grantfirl @dustinswales @mzhangw @mkavulich May I ask if you can review the PR? We need this fix for operational implementation, thank you very much!

**Comment by grantfirl** [comment]
Supercedes https://github.com/ufs-community/ccpp-physics/pull/149

**Review by grantfirl — APPROVED** [review]

**Comment by grantfirl** [comment]
@Qingfu-Liu @junwang-noaa I'll run RTs for this alone to verify behavior. Then, assuming no BL changes, I'd like to see it combined with #150, which also doesn't change BLs.

**Comment by grantfirl** [comment]
OK, RTs are all successful. I'm going to ask Dom to combine this with #150 for final tests/merge.

**Comment by Qingfu-Liu** [comment]
@junwang-noaa and @grantfirl Since this PR#169 is merged to PR#150, I am not sure who should create a UFS WM PR for PR#150?

**Comment by junwang-noaa** [comment]
@Qingfu-Liu I see Dom already created a ufs wm [PR#2066](https://github.com/ufs-community/ufs-weather-model/pull/2066).

**Comment by Qingfu-Liu** [comment]
@junwang-noaa Thanks for the information.

**Pull request merged**
