### PR TITLE
NCAR/main PR #972

### PR DESCRIPTION
**Pull request by dustinswales**
This PR adds continuous integration tests to run the ccpp_prebuild script for all available host models, currently NCAR/ccpp-scm and NOAA-EMC/fv3atm.

For each host-model, the scripts do the following:
- Check out local ccpp-physics code (save github URL and branch information)
- Check out host-model interface and ccpp_prebuild
- Switch host-model ccpp-physics to use local ccpp-physics
- Set up Python environment (v3.8.5)
- Run ccpp_prebuild.py

This is done for all commits, alerting developers to changes that break the host-model coupling to the ccpp-physics

### CODE REVIEW

**Review by grantfirl — APPROVED** [review]

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
@dustinswales this pr is only to do with ccpp git action. can we coordinate to combine with [ufs-wm pr 1486](https://github.com/ufs-community/ufs-weather-model/pull/1486) ?

**Comment by jkbk2004** [comment]
Or since only yaml file changes for ccpp git workflow/action, @ChunxiZhang-NOAA @dustinswales we are ok tp combine this pr to either #18 or #19. I think this option is easier. can we agree?

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 I would like to keep each ccpp-physics PR separate. The best option is to combine with ufs-wm PR[#1486](https://github.com/ufs-community/ufs-weather-model/pull/1486).

**Comment by dustinswales** [comment]
@jkbk2004 @ChunxiZhang-NOAA I have no preference. Whatever is easiest for you from a code management perspective.

**Comment by jkbk2004** [comment]
@dustinswales next good chance to merge in this pr is to combine with [ufs wm pr 1492](https://github.com/ufs-community/ufs-weather-model/pull/1492). Can you create a fv3atm fork branch containing this pr and create a pr to fv3atm? So that we can coordinate to combine with [ufs wm pr 1492](https://github.com/ufs-community/ufs-weather-model/pull/1492). @ChunxiZhang-NOAA that's a way we can go, right?

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 Yes, that's the best way, thanks.

**Comment by dustinswales** [comment]
@jkbk2004 @ChunxiZhang-NOAA 
See [fv3atm 603](https://github.com/NOAA-EMC/fv3atm/pull/603)

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA can you merge in this pr? so that we can move on to merge in down stream prs on fv3atm and weather model side.

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 Sure. Done.

**Pull request merged**
