### PR TITLE
Update documentation for new NSSL-MP namelist parameters

### PR DESCRIPTION
**Pull request by MicroTed**
Add documentation lines for new namelist parameters (nssl_alphar, nssl_ehw0, nssl_ehlw0) with a minor name tweak.
Also, nssl_params(14) is used by another version, so this is changed to nssl_params(15) for consistency (no effect)

Follow-up on https://github.com/ufs-community/ccpp-physics/pull/45 (@JiliDong-NOAA)

 - Also update the CODEOWNERS file to reflect the latest physics POCs in https://docs.google.com/spreadsheets/d/14y0Th_sSpCqlssEMNfSZ_Ni9wrpPqfpPY0kRG7jCZB8/edit?usp=sharing

### CODE REVIEW

**Comment by MicroTed** [comment]
Question: Does SCM need to be updated now, too, or is that a bridge to cross later?

OK, done here: https://github.com/NCAR/ccpp-scm/pull/385

**Comment by grantfirl** [comment]
> Question: Does SCM need to be updated now, too, or is that a bridge to cross later?
> 
> OK, done here: [NCAR/ccpp-scm#385](https://github.com/NCAR/ccpp-scm/pull/385)

Typically, CCPP code managers handle any changes in FV3 that need to be brought over to the SCM, but thanks for going the extra mile.

**Review by grantfirl — APPROVED** [review]

**Review by Qingfu-Liu — APPROVED** [review]

**Comment by grantfirl** [comment]
@MicroTed I'd like to ask you if you'd be willing to bring in the changes from #76 to this PR to reduce code management workload. That PR changes baselines, but it is only a build system change for the UGWP scheme. I would be responsible for testing the combined PR to make sure it is behaving as expected.

**Comment by MicroTed** [comment]
> I'd like to ask you if you'd be willing to bring in the changes from #76 to this PR to reduce code

@grantfirl Sure, that shouldn't be much trouble.

Done.

**Comment by grantfirl** [comment]
@MicroTed Please update this branch to the latest ufs/dev branch when you get a chance.

**Comment by MicroTed** [comment]
> @MicroTed Please update this branch to the latest ufs/dev branch when you get a chance.

@grantfirl I am getting a conflict in ccpp/physics/CMakeLists.txt. The second half is from #76, and I think that was taken back out of this PR? So should whole thing be removed or no? 

Never mind -- I forgot to pull my branch, haha

**Comment by grantfirl** [comment]
> > @MicroTed Please update this branch to the latest ufs/dev branch when you get a chance.
> 
> @grantfirl I am getting a conflict in ccpp/physics/CMakeLists.txt. The second half is from #76, and I think that was taken back out of this PR? So should whole thing be removed or no?
> 
> ```
> <<<<<<< HEAD
> # Reduce optimization for mo_gas_optics_kernels.F90 (to avoid an apparent compiler bug with Intel 19+)
> if(${LOCAL_CURRENT_SOURCE_DIR}/physics/rte-rrtmgp/rrtmgp/kernels/mo_gas_optics_kernels.F90 IN_LIST SCHEMES_OPENMP_OFF AND
>    CMAKE_BUILD_TYPE STREQUAL "Release" AND ${CMAKE_Fortran_COMPILER_ID} STREQUAL "Intel")
>   SET_SOURCE_FILES_PROPERTIES(${LOCAL_CURRENT_SOURCE_DIR}/physics/rte-rrtmgp/rrtmgp/kernels/mo_gas_optics_kernels.F90
>                               APPEND_STRING PROPERTY COMPILE_FLAGS " ${CMAKE_Fortran_FLAGS_PHYSICS} -O1")
> endif()
> 
> # Increase optimization for ugwp_driver_v0.F
> if(CMAKE_BUILD_TYPE STREQUAL "Release" AND ${CMAKE_Fortran_COMPILER_ID} STREQUAL "Intel")
>   SET_SOURCE_FILES_PROPERTIES(${LOCAL_CURRENT_SOURCE_DIR}/physics/ugwp_driver_v0.F
>                               APPEND_STRING PROPERTY COMPILE_FLAGS " ${CMAKE_Fortran_FLAGS_PHYSICS} -fp-model=fast -fprotect-parens -fimf-precision=high")
> endif()
> 
> =======
> >>>>>>> ufs/ufs/dev
> ```

Ya, all CMakeLists.txt changes should be removed. So, you can delete everything between  the `<<<<<<` and `>>>>>>`, then `git add` the file and `git commit`. This should fix the conflict.

**Comment by zach1221** [comment]
Testing on UFS-WM PR [#1775](https://github.com/ufs-community/ufs-weather-model/pull/1775) is complete. Feel free to go ahead and merge this sub-pr. @grantfirl

**Comment by jkbk2004** [comment]
@Qingfu-Liu @dustinswales If you have permission, please, go ahead to merge this pr.

**Pull request merged**
