### PR TITLE
Fix bug in aerinterp read routines that break 32-bit physics and pass NetCDF errors up through errflg&errmsg

### LINKED ISSUE #83: 32-bit physics crashes in aerinterp due to type mismatch in NetCDF calls.
# Description

The aerinterp routines use `real*4` arrays to read `real*8` data when compiled with 32-bit physics. This causes a crash because of the NetCDF Fortran 77 interface, which does not know which datatype it has.

## Steps to Reproduce

1. Create a 32-bit physics version of the RRFS 13km conus ufs-weather-model regression tests.
2. Run it and you'll see the crash.
3. Run the gnu version of the test through valgrind, and you'll see where and why it crashes.

## Additional Context

Tested with hera.gnu and hera.intel using the FV3_HRRR suite in the UFS regression tests. Must compile with 32-bit physics to trigger the error.

## Output

N/A

### LINKED ISSUE #84: aerinterp routines do not pass NetCDF errors up through errmsg and errflg
# Description

There are NetCDF read routines in aerinterp.F90, but they do not detect errors or report the errors through errmsg or errflg.

## Steps to Reproduce

Read the code?

## Additional Context

This was discovered while debugging #83

## Output

N/A

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
The aerinterp routines use `real*4` arrays to read `real*8` data when compiled with 32-bit physics. This causes a crash because of the NetCDF Fortran 77 interface, which does not know which datatype it has. These changes:

1. Switch to the Fortran 90 interface which can do type conversion when reading.
2. Detects NetCDF errors and returns them in errflg and errmsg.

- Fixes #83
- Fixes #84

### CODE REVIEW

**Review by grantfirl — APPROVED** [review]
Looks good to me.

**Comment by AnningCheng-NOAA** [comment]
looks good to me. Approved

**Review by dustinswales — APPROVED** [review]
@SamuelTrahanNOAA Thanks for these changes.

**Comment by SamuelTrahanNOAA** [comment]
@AnningCheng-NOAA 
> looks good to me. Approved

You didn't actually approve the PR. You just typed the word "Approved." To approve the pull request, you need to submit an approving review.

**Review by AnningCheng-NOAA — APPROVED** [review]
looks good. @SamuelTrahanNOAA, Thanks.

**Review by Qingfu-Liu — APPROVED** [review]

**Comment by grantfirl** [comment]
@SamuelTrahanNOAA Please merge in the latest ufs/dev branch in preparation for the merge queue.

**Comment by SamuelTrahanNOAA** [comment]
> Please merge in the latest ufs/dev branch in preparation for the merge queue.

I already did that. Also, I validated against the baseline after merging ufs/dev.

**Comment by grantfirl** [comment]
> > Please merge in the latest ufs/dev branch in preparation for the merge queue.
> 
> I already did that. Also, I validated against the baseline after merging ufs/dev.

@SamuelTrahanNOAA Ah, I see that now. Sorry for spamming and thanks for being on top of it.

**Comment by zach1221** [comment]
Testing is now complete on UFS-WM PR #1797. @SamuelTrahanNOAA @grantfirl as this ccpp-physics sub-component PR is approved, please feel free to merge it.

**Pull request merged**
