### PR TITLE
Convert GFS DDTs from blocked data structures to contiguous arrays (aka update GFS_debug.F90)

### PR DESCRIPTION
**Pull request by climbfuji**
### Description

In the UFS atmospheric component fv3atm and submodules, convert internal GFS DDTs from blocked data structures to contiguous arrays. This excludes the (external) GFS_extdiag and GFS_restart DDTs. Also remove the GFS_Data super DDT and use the individual DDTs directly.

For ccpp-physics, this only affects the (apparently unused) `GFS_debug.{f90,meta}` files. We could consider removing them entirely instead of updating them, since they don't get used?

### Testing

See https://github.com/ufs-community/ufs-weather-model/pull/2183

### Associated PRs:

https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/330
https://github.com/ufs-community/ccpp-physics/pull/183
https://github.com/NOAA-EMC/fv3atm/pull/798
https://github.com/ufs-community/ufs-weather-model/pull/2183

### CODE REVIEW

**Review by Qingfu-Liu — APPROVED** [review]

**Comment by grantfirl** [comment]
@climbfuji I'd like to keep these in the repo since they can be useful. You've already done the work, so why not?

**Comment by climbfuji** [comment]
> @climbfuji I'd like to keep these in the repo since they can be useful. You've already done the work, so why not?

Fine with me. We should have a regression test though to make sure they are still working

**Comment by climbfuji** [comment]
This PR is now ready for review

**Review by grantfirl — APPROVED** [review]

**Review by Qingfu-Liu — APPROVED** [review]

**Review by dustinswales — APPROVED** [review]

**Comment by climbfuji** [comment]
@dusanjovic-noaa @dustinswales @grantfirl I just pushed commit https://github.com/ufs-community/ccpp-physics/pull/183/commits/afa2bc0632bd1e8a14740da484a431eadc56ec68 (and corresponding submodule pointer updates all the way up to  ufs-weather-model).

I was able to build a spack-stack environment "somewhat similar" to that on WCOSS2 on S4 using intel@19.0.5. WIth that environment, I ran into issues (segfaults, memory corruption) in `clm_lake.f90` around the `lakeini` routine. That's probably the same part of the code that the WCOSS2 runs had problems with.

With the changes I made in commit afa2bc0, the runs went through on S4 (with the `-check nopointer` flag removed). Could you give this a try, please?

**Comment by FernandoAndrade-NOAA** [comment]
Testing on [2183](https://github.com/ufs-community/ufs-weather-model/pull/2183) has completed successfully, please continue with the merge process.

**Comment by zach1221** [comment]
Adding @grantfirl . Grant, are you able to merge for us?

**Pull request merged**
