### PR TITLE
Lightning threat indexes

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
This is part of a collection of PRs to add lightning threat indexes to the RRFS. The algorithm was originally ported from HRRR to the GFDL_atmos_cubed_sphere NGGPS diagnostics, using the w variable in both implementations. I've moved it to CCPP's maximum hourly diagnostics, but it still needs w in the formulation, so I've added the dynamical core's `w` variable as `wgrs`.

Issue is here: https://github.com/ufs-community/ufs-weather-model/issues/1632

This work originates from @welewis69 at University of Wisconsin-Madison, who put it in the NGGPS diagnostics. I moved it to CCPP for this PR.

### CODE REVIEW

**Review by grantfirl — CHANGES_REQUESTED** [review]
The code changes look good. I'll approve once standard name changes from https://github.com/NOAA-EMC/fv3atm/pull/628 have been addressed and the `w` controversy is settled.

**Review by ChunxiZhang-NOAA — APPROVED** [review]
Looks good.

**Comment by SamuelTrahanNOAA** [comment]
@grantfirl - I think we've settled on using w, since there isn't any other way to get the unsmoothed non-hydrostatic vertical wind. Also, I adjusted names based on your requirements. Could you please re-review, and let me know if everything is okay now?

**Comment by ChunxiZhang-NOAA** [comment]
@SamuelTrahanNOAA @welewis69 It is still not clear to me if the unsmoothed w is the best choice since all physics schemes use smoothed w including the microphysics schemes.

**Comment by SamuelTrahanNOAA** [comment]
> @SamuelTrahanNOAA @welewis69 It is still not clear to me if the unsmoothed w is the best choice since all physics schemes use smoothed w including the microphysics schemes.

For anything that may eventually affect the prognostic variables, you *have* to used the smoothed vertical velocity (vvl) so that the smoothing can be used to resolve model stability issues. Also, we must be consistent among physics schemes whose output feeds back into the prognostic variables, otherwise you'll get spurious results when one thinks there's an updraft and another thinks there's nothing.

This diagnostic does *not* feed back into the prognostic variables, ever, and it does need the highest possible precision of w. Smoothing will eliminate the sharp peaks of high w values that are needed to simulate lightning.

**Comment by ChunxiZhang-NOAA** [comment]
@SamuelTrahanNOAA Thanks for the interpretation. It is good to use unsmoothed w then.

**Comment by SamuelTrahanNOAA** [comment]
> Thanks for the interpretation. It is good to use unsmoothed w then.

It may also be good to document somewhere that people should not use the *unsmoothed* vertical velocity unless they're generating purely diagnostic fields. I hope that putting "unsmoothed" in the name will be enough for that.

**Review by dustinswales — APPROVED** [review]
Looks good.

**Review by grantfirl — APPROVED** [review]

**Comment by jkbk2004** [comment]
@grantfirl @dustinswales @Qingfu-Liu All tests are done on https://github.com/ufs-community/ufs-weather-model/pull/1642. Please, go ahead to merge this pr.

**Pull request merged**
