### PR TITLE
bug fix for hybrid-EDMF PBL scheme

### PR DESCRIPTION
**Pull request by ChangHung-CWB**
The conditional statement for calculating the Prandtl number were modified to correctly distinguish the boundary layer stability.
A more detailed description of modification and experiment results can be found in the attach file.
[modified hedmf.pdf](https://github.com/ufs-community/ccpp-physics/files/10370929/modified.hedmf.pdf)

### CODE REVIEW

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by ChunxiZhang-NOAA** [comment]
@JongilHan66 Please review this bugfix at your convenience.

**Comment by JongilHan66** [comment]
That's not bug:

In hybrid-EDMF, the unstable pbl (pblflg=.T.) is divided into strongly unstable pbl (pcnvflg=.T. for z/L<-0.5) and weakly unstable pbl (ublflg=.T. for z/L>-0.5). For strongly unstable pbl (pcnvflg=T), EDMF is used and we should not include nonlocal countergradient mixing term (cfac*vk*sfcfrac) in computing Prandtl number. For weakly unstable pbl(ublflg=T), EDCG scheme is used and the nonlocal countergradient mixing term (cfac*vk*sfcfrac) should be included in computing Prandtl number.

**Comment by ChunxiZhang-NOAA** [comment]
@JongilHan66 @ChangHung-CWB Thank you Jongil. I will close this PR then.

**Comment by yangfanglin** [comment]
Chunxi, PLease wait for CWB's response before you close this PR

**Comment by ChunxiZhang-NOAA** [comment]
@yangfanglin Ok, I will not close it until CWB's response.

**Comment by ChangHung-CWB** [comment]
@JongilHan66 Thanks for your clear interpretation.  We get more understanding the scheme now. Thanks again.
@ChunxiZhang-NOAA Please close the PR. Thanks.

**Pull request closed without merging**
