### PR TITLE
NCAR-main PR#956

### PR DESCRIPTION
**Pull request by dustinswales**
This PR is identical to[ NCAR #956](https://github.com/NCAR/ccpp-physics/pull/956)

This PR addresses several outstanding issues:
- Remove all instances of physparam.f. [448](https://github.com/NCAR/ccpp-physics/issues/488)
- Bug in gcycle.F90. [672](https://github.com/NCAR/ccpp-physics/issues/672)
- Missing metadata hooks in gsl drag suite. [764](https://github.com/NCAR/ccpp-physics/issues/764)
- Fix file extension for pre-processor directives. (.f90->.F90). [886](https://github.com/NCAR/ccpp-physics/issues/886)
- Replace "stop" statements with CCPP error handling. [913](https://github.com/NCAR/ccpp-physics/issues/913)
Along with the physparam.f cleanup in #488, instances of physcons.f were removed for the touched subroutines, mostly the rrtmg radiation.

### CODE REVIEW

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
@grantfirl please, go ahead to approve on this pr as well.

**Comment by jkbk2004** [comment]
@dustinswales still need to sync all the way up to downstream branches though.

**Review by grantfirl — APPROVED** [review]

**Comment by dustinswales** [comment]
@jkbk2004 All up to date and synced

**Comment by zach1221** [comment]
Hi, @ChunxiZhang-NOAA . Tests are done on PR [1604](https://github.com/ufs-community/ufs-weather-model/pull/1604), can you merge this PR?

**Comment by jkbk2004** [comment]
@grantfirl if possible, can you go ahead to merge the pr?

**Comment by dustinswales** [comment]
@jkbk2004 Sorry, I missed this somehow. Thanks @grantfirl!

**Pull request merged**
