### PR TITLE
Bring external land model support

### PR DESCRIPTION
**Pull request by uturuncoglu**
This PR aims to bring support for external land component (i.e. Noah MP). At this point, the interaction between atmosphere and ccpp/physics is unidirectional and ccpp/physics does not receive any information from external land component and only allow sending required fields to land component. The two way interaction, will be implemented in the later stage of the JTTI project.

### CODE REVIEW

**Review by grantfirl — APPROVED** [review]
I don't see any issues from a CCPP point of view.

**Review by dustinswales — APPROVED** [review]
These changes look good to me.

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
Tests are done with [ufs-wm PR 1443](https://github.com/ufs-community/ufs-weather-model/pull/1443). @ChunxiZhang-NOAA can you merge in this PR?

**Comment by ChunxiZhang-NOAA** [comment]
> Tests are done with [ufs-wm PR 1443](https://github.com/ufs-community/ufs-weather-model/pull/1443). @ChunxiZhang-NOAA can you merge in this PR?

@jkbk2004 Done.

**Pull request merged**
