### PR TITLE
fix for RUC LSM imprecision issue

### LINKED ISSUE #5: module_sf_ruclsm imprecision breaks gfortran in debug mode for RRFS tests
# Description

The module_sf_ruclsm has comparisons to zero, which break the code when numbers are very close to 0, such as 1e-322. This happens with the gfortran compiler when compled -DDEBUG=ON since the option to truncate subnormal numbers is turned off.

## Steps to Reproduce

1. Fix bugs in the fv_regional_bc.F90 that prevent RRFS from running in DEBUG=ON mode
2. Run one of the RRFS tests in DEBUG=ON mode with the gnu compiler on Hera
3. View the resulting core dumps using gdb
4. Sadness

## Additional Context

The model will fail much earlier, due to known bugs. I'm about to submit a PR and some issues to fix that.

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
The module_sf_ruclsm.F90 has comparisons to zero, which break the code when numbers are very close to 0, such as 1e-322. This happens with the gfortran compiler when compled with `-DDEBUG=ON` since the option to truncate subnormal numbers is turned off. It might also happen if the ruc lsm was run in double precision, but I have not seen that yet. My fix is truncate subnormal numbers manually, for the two variables that cause trouble. This new code is in the "sanity checks" regions of lsm_ruc.F90, as requested by @tanyasmirnova.

Fixes #5

### CODE REVIEW

**Review by grantfirl — APPROVED** [review]

**Review by ChunxiZhang-NOAA — APPROVED** [review]

**Comment by SamuelTrahanNOAA** [comment]
Codeowner @tanyasmirnova has requested that:

1. The sanity checks should be moved to lsm_ruc.F90's sanity check block where they belong.
2. Two "snow on ice" variables should have the same sanity check. (By luck alone, the gfortran debug test did not encounter subnormal snow on ice numbers.)

I'm testing this in the fork (https://github.com/NOAA-GSL/ccpp-physics/pull/163) and I'll apply the fix to this PR as soon as those tests pass.

**Review by tanyasmirnova — APPROVED** [review]

**Comment by grantfirl** [comment]
@SamuelTrahanNOAA Since https://github.com/ufs-community/ccpp-physics/pull/13 was merged, I think that this one is the next in the UFS merge queue. Please pull in the latest ufs/dev branch to get ready for testing when you get a chance.

**Review by tanyasmirnova — APPROVED** [review]

**Comment by SamuelTrahanNOAA** [comment]
@grantfirl The ccpp-physics seems to be ahead of the higher-level repositories. Are you sure #13 was supposed to be merged?

**Comment by grantfirl** [comment]
Super-repos are still in the process of merging their respective PRs.

**Comment by SamuelTrahanNOAA** [comment]
It looks like the only changes are in ccpp/physics, so I can start testing despite the out-of-sync repositories.

**Comment by jkbk2004** [comment]
@ChunxiZhang-NOAA @SamuelTrahanNOAA [cubed sphere pr 219](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/219) was merged in. We can move on to merge this pr.

**Comment by grantfirl** [comment]
@jkbk2004 I can merge this if necessary. I think that ordinarily, @ChunxiZhang-NOAA should have that responsibility for this fork/branch, but @dustinswales and I have the capability if there is ever time pressure.

**Comment by jkbk2004** [comment]
@grantfirl sure! please, go ahead. so that @SamuelTrahanNOAA can move to downstream.

**Comment by ChunxiZhang-NOAA** [comment]
> @jkbk2004 I can merge this if necessary. I think that ordinarily, @ChunxiZhang-NOAA should have that responsibility for this fork/branch, but @dustinswales and I have the capability if there is ever time pressure.

@grantfirl  Thanks for merging the PR into this fork timely. I was in a meeting.

**Pull request merged**
